name: MediCare Pro - CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./backend
        run: npm install

      - name: Check Backend Files
        working-directory: ./backend
        run: |
          echo "Verification backend..."
          node -c app.js
          echo "Backend OK !"

  test-frontend:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Angular
        working-directory: ./frontend
        run: npm run build

      - name: Verify Build
        run: |
          echo "Verification build Angular..."
          ls frontend/dist/
          echo "Build OK !"

  build-and-push:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/medicare-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/medicare-frontend:latest

      - name: Pipeline Success
        run: |
          echo "==============================="
          echo "  PIPELINE CI/CD REUSSI !"
          echo "  Backend  : ${{ secrets.DOCKER_USERNAME }}/medicare-backend:latest"
          echo "  Frontend : ${{ secrets.DOCKER_USERNAME }}/medicare-frontend:latest"
          echo "==============================="